default_config:

logger:
  default: warning
  logs:
    custom_components.stromligning: debug
    pystromligning: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:
